#timeseries and bz are lists generated by csheet_integrator.py
import matplotlib.pyplot as plt
from glob import glob
import numpy as np
import supermag
from csheet_integrator import gmp_timeseries
from spacepy.coordinates import Coords
from spacepy.time import Ticktock
import pandas as pd

#locates all txt files and compiles them into a list
files = glob('/home/richard/Desktop/github/precursorDB/data/supermag/*.txt')   

#list files
for i, f in enumerate(files):
	print(f"#{i}\t{f}") 

#choose event
iFile = int(input("Which event?"))
iFile
files[iFile]

#get keys from supermag dictionary
mags = supermag.SuperMag(files[iFile])
mags.keys()

#open events excel sheet
data = pd.read_excel('/home/richard/Desktop/github/precursorDB/docs/SSC_events.xlsx')

#retrieve satellite information from excel sheet for use in integrator
IMFdz = float(data['Bz,init (nT)'][iFile])
IMFuz = float(data['Bz,final (nT)'][iFile]) 
IMFdy = float(data['By,init (nT)'][iFile])
IMFuy = float(data['By,final (nT)'][iFile]) 
Vsw = float(data['Usw (km/s)'][iFile]) 

#run integrator
timeseries = gmp_timeseries(IMFdz, IMFuz, IMFdy, IMFuy, Vsw)

#make list of by and bz values in gsm coordinates
By_gsm = timeseries[:,1]
Bz_gsm = timeseries[:,2]
B_gsm = []

#compile all the gsm values (bx = 0) and put them into an array
for by in By_gsm:
	for bz in Bz_gsm:
		B_gsm.append([0, by, bz])

#turn array into spacpy Coords object
cvals = Coords(B_gsm, 'GSM', 'car')

#temporary time list until I can figure out how to input datetime information
time = []
i = 0
for item in cvals:
	time.append(i)
	i += 1
	
cvals.ticks = Ticktock(time, 'UNX')

#convert to mag coordinate system
B_mag = cvals.convert('MAG', 'sph')


