#timeseries and bz are lists generated by csheet_integrator.py
import matplotlib.pyplot as plt
import supermag
from glob import glob
import matplotlib.dates as mdates
from spacepy.plot import style

#locates all txt files and compiles them into a list
files = glob('precursorDB/data/supermag/*.txt')   

#list files
for i, f in enumerate(files):
	print(f"#{i}\t{f}") 

#choose file
iFile = int(input("What file do you choose?"))
iFile
files[iFile]

#creates a dictionary from the selected file and retrieves the keys from that dictionary
mags = supermag.SuperMag(files[iFile])
mags.keys()

#creates and prints a list of stations
stations = list(mags.keys())[1:]
for j, g in enumerate(stations):
	print(f"#{j}\t{g}") 

#choose station
iStation = int(input("What station do you choose?"))
iStation
stations[iStation]

#accounts for the difference in time between SSC in simulation and real world data
offset = int

#returns plot of data 
style()
plt.ion()
Bz = plt.plot(mags['time'], mags[stations[iStation]]['bx'])
plt.style.use('bmh')
plt.title(r'$B_z$'+' from '+str(stations[iStation])+' during the '+str(mags['time'][200].year)+'/'+str(mags['time'][200].month)+'/'+str(mags['time'][200].day)+' Event')
plt.ylabel(r'$B_z \ (nT)$')
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
plt.xlabel('UT')

