'''
-sync x-values of simulation data, xlist, and supermag data, mags['time'] so the SSCs happen at the same time
'''


import matplotlib.pyplot as plt
import supermag
#import xlist, ylist
#xlist and ylist are lists generated by Atharva's code

print("enter date (YYYYMMDD):")
file = str(input()+"_data.txt")
#prompt to choose which file to open

print("which magnetometer?")
station = input()
#prompt to choose which magnetometer to take data from

mags = supermag.SuperMag('precursorDB/data/supermag/'+file)
mags.keys()
#creates a dictionary from the selected file and retrieves the keys from that dictionary

offset = int
#accounts for the difference in time between SSC in simulation and real world data

plt.ion()
plt.plot(mags['time'], mags[station]['bz'])
#plt.plot(xlist - offset, ylist)
#returns plot of data 
